name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"
run-name: ${{ github.actor }} / infra plan and apply 🚀

on: workflow_dispatch

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      BUILD_DB_HOST: localhost
      BUILD_DB_NAME: themepark
      BUILD_DB_USERNAME: 'username'
      BUILD_DB_PASSWORD: 'password'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build
        run: |
          export MYSQL_DATABASE=$BUILD_DB_NAME
          export MYSQL_USER=$BUILD_DB_USERNAME
          export MYSQL_PASSWORD=$BUILD_DB_PASSWORD
          docker run -d --name db -e MYSQL_RANDOM_ROOT_PASSWORD=yes  -e MYSQL_DATABASE -e MYSQL_USER -e MYSQL_PASSWORD -p 3306:3306 mysql:8.0

          export DB_URL=`echo jdbc:mysql://$BUILD_DB_HOST:3306/$BUILD_DB_NAME`
          export DB_USERNAME=$BUILD_DB_USERNAME
          export DB_PASSWORD=$BUILD_DB_PASSWORD
          sed -i "s/CI_PIPELINE_IID/${{ github.run_id }}/" ./src/main/resources/application.yml
          sed -i "s/CI_COMMIT_SHORT_SHA/${{ github.sha }}/" ./src/main/resources/application.yml
          sed -i "s/CI_COMMIT_BRANCH/${{ github.ref_name }}/" ./src/main/resources/application.yml
          sed -i "s/HIBERNATE-DDL-AUTO/create/" ./src/main/resources/application.yml
          ./gradlew build
      - name: smoke test
        run: |
          export DB_URL=`echo jdbc:mysql://$BUILD_DB_HOST:3306/$BUILD_DB_NAME`
          export DB_USERNAME=$BUILD_DB_USERNAME
          export DB_PASSWORD=$BUILD_DB_PASSWORD
          java -jar ./build/libs/theme-park-ride-gradle.jar &
          sleep 10
          curl http://localhost:5000/actuator/health | grep "UP"
      - name: unit test
        run: |
          export DB_URL=`echo jdbc:mysql://$BUILD_DB_HOST:3306/$BUILD_DB_NAME`
          export DB_USERNAME=$BUILD_DB_USERNAME
          export DB_PASSWORD=$BUILD_DB_PASSWORD
          ./gradlew test
          grep testsuite build/test-results/test/TEST-com.exemple.ThemeParkRideGradleApplicationTests.xml